version: '3'

networks:
  ldap_network:
    driver: bridge
services:
  openldap:
    image: osixia/openldap:latest
    container_name: openldap
    environment:
      LDAP_BASE_DN: "dc=example,dc=org"
      LDAP_ORGANISATION: "Example Organization"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_TLS: "false"             # deactivate TLS for the LDAP server
    volumes:
      - ./ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/50-bootstrap.ldif
    networks:
      - ldap_network
    ports:
      - "389:389"                   # default port for unsecured LDAP
    command: --copy-service
    restart: unless-stopped
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: openldap
      PHPLDAPADMIN_HTTPS: "false"   # deactivate HTTPS
    networks:
      - ldap_network
    ports:
      - "8081:80"
    restart: unless-stopped
    depends_on:
      - openldap

  postgres:
    image: 'postgres:15.7'
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb
#    environment:
#      - 'POSTGRES_DB=wherewasi'
#      - 'POSTGRES_PASSWORD=wherewasi'
#      - 'POSTGRES_USER=wherewasi'
    environment:
      POSTGRES_USER: wherewasi
      POSTGRES_DB: wherewasi
      POSTGRES_PASSWORD: wherewasi
    ports:
      - '6543:5432'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8082:8080