# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '*.md'
      - '.github/workflows/fly-deploy.yml'
      - '.github/workflows/native-image.yml'

jobs:
  build:
    name: Build with GraalVM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'      # See 'Options' for more details
          distribution: 'graalvm-community' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven'
      - name: Build with Maven
        run: mvnd clean package -Pproduction -Dvaadin.force.production.build=true -Dparallel=all -DperCoreThreadCount=false -DthreadCount=16 -T 1C -e
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: where-was-i-binary
          path: target/where-was-i

  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    needs: build
    concurrency: deploy-group    # optional: ensure only one action runs at a time
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: where-was-i-binary
          path: target/
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}