name: Native Image

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths-ignore:
      - 'Makefile'
      - '*.md'
      - '.github/workflows/fly-deploy.yml'
      - '.github/workflows/fly-restart.yml'
      - '.github/workflows/fly-db-backup.yml'

# See official GraalVM Action: https://github.com/graalvm/setup-graalvm
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '23'      # See 'Options' for more details
          distribution: 'graalvm' # See 'Supported distributions' for available options
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Verify Versions
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version
          docker compose version
      - name: Docker Compose Initialization
        run: docker compose up -d
      - name: Build
        run: mvn -Dparallel=all -DperCoreThreadCount=false -DthreadCount=16 -T 1C -e clean verify
      - name: Build Native Binary  # https://graalvm.github.io/native-build-tools/latest/maven-plugin.html
        run: mvn -Pproduction  -Dvaadin.force.production.build=true -Pnative  -DskipTests=true  -Dparallel=all -DperCoreThreadCount=false -DthreadCount=16 -T 1C -e clean native:compile

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: joostvdg
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

#      - name: Build and push
#        uses: docker/build-push-action@v6
#        with:
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: |
#            user/app:latest
#            user/app:1.0.0
#            ghcr.io/user/app:latest
#            ghcr.io/user/app:1.0.0
      - name: Build Native Image Container Image
        run: make ndocker